{"uuid":"221c9a16-13b4-4c69-bd18-371c6cc2ef8d","historyId":null,"status":"broken","statusDetails":{"message":"Oops...we found an error preparing this test file:\n\n  > cypress/e2e/tasks.cy.js\n\n","trace":"\n\nError: Webpack Compilation Error\nModule build failed (from ../../.cache/Cypress/13.8.1/Cypress/resources/app/node_modules/babel-loader/lib/index.js):\nSyntaxError: /home/pavani/workspace/cypress_qaexperience/cypress/e2e/tasks.cy.js: Unexpected token, expected \",\" (34:34)\n\n  32 |             cy.createTask('Ler um livro')\n  33 |             cy.contains('main div p', 'Ler um livro')\n> 34 |               .should('be.visible'dsds)\n     |                                   ^\n  35 |             // cy.wait (9999)\n  36 |           })\n  37 |         \n    at handle (/home/pavani/.cache/Cypress/13.8.1/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-preprocessor/dist/index.js:212:23)\n    at finalCallback (/home/pavani/.cache/Cypress/13.8.1/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:441:32)\n    at /home/pavani/.cache/Cypress/13.8.1/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:505:17\n    at /home/pavani/.cache/Cypress/13.8.1/Cypress/resources/app/node_modules/webpack/lib/HookWebpackError.js:68:3\n    at Hook.eval [as callAsync] (eval at create (/home/pavani/.cache/Cypress/13.8.1/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/pavani/.cache/Cypress/13.8.1/Cypress/resources/app/node_modules/tapable/lib/Hook.js:18:14)\n    at Cache.storeBuildDependencies (/home/pavani/.cache/Cypress/13.8.1/Cypress/resources/app/node_modules/webpack/lib/Cache.js:122:37)\n    at /home/pavani/.cache/Cypress/13.8.1/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:501:19\n    at Hook.eval [as callAsync] (eval at create (/home/pavani/.cache/Cypress/13.8.1/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/pavani/.cache/Cypress/13.8.1/Cypress/resources/app/node_modules/tapable/lib/Hook.js:18:14)\n    at /home/pavani/.cache/Cypress/13.8.1/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:498:23\n    at Compiler.emitRecords (/home/pavani/.cache/Cypress/13.8.1/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:919:5)\n    at /home/pavani/.cache/Cypress/13.8.1/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:490:11\n    at /home/pavani/.cache/Cypress/13.8.1/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:885:14\n    at Hook.eval [as callAsync] (eval at create (/home/pavani/.cache/Cypress/13.8.1/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)\n    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/pavani/.cache/Cypress/13.8.1/Cypress/resources/app/node_modules/tapable/lib/Hook.js:18:14)\n    at /home/pavani/.cache/Cypress/13.8.1/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:882:27\n    at /home/pavani/.cache/Cypress/13.8.1/Cypress/resources/app/node_modules/neo-async/async.js:2818:7\n    at done (/home/pavani/.cache/Cypress/13.8.1/Cypress/resources/app/node_modules/neo-async/async.js:3522:9)\n    at alreadyWritten (/home/pavani/.cache/Cypress/13.8.1/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:714:8)\n    at /home/pavani/.cache/Cypress/13.8.1/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:802:19\n    at /home/pavani/.cache/Cypress/13.8.1/Cypress/resources/app/node_modules/graceful-fs/graceful-fs.js:123:16\n    at /home/pavani/.cache/Cypress/13.8.1/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:123:16\n    at /home/pavani/.cache/Cypress/13.8.1/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:123:16\n    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3)\n\nThis occurred while Cypress was compiling and bundling your test code. This is usually caused by:\n\n- A missing file or dependency\n- A syntax error in the file or one of its dependencies\n\nFix the error in your code and re-run your tests."},"stage":"finished","attachments":[{"name":"video recording","type":"video/mp4","source":"d2ad40d6-356d-41cd-b167-d312cd718170-attachment.mp4"}],"parameters":[],"labels":[{"name":"suite","value":"tasks.cy.js"}],"links":[],"start":null,"name":"Oops...we found an error preparing this test file: tasks.cy.js","fullName":"Oops...we found an error preparing this test file: tasks.cy.js","stop":null}